/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 25 21:12:12 GMT 2020
 */

package br.com.teste.gft.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.teste.gft.util.StringUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StringUtils_ESTest extends StringUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = StringUtils.removeCaracteresEspeciais("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        StringUtils.removeCaracteresEspeciais((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.teste.gft.util.StringUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = StringUtils.removeCaracteresEspeciais("6.NSN");
      assertEquals("6 NSN", string0);
  }
}
