/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 25 21:08:33 GMT 2020
 */

package br.com.teste.gft.enuns;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.teste.gft.enuns.PeriodoEnum;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PeriodoEnum_ESTest extends PeriodoEnum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PeriodoEnum periodoEnum0 = PeriodoEnum.getPeriodoByDescricao("noite");
      assertEquals(PeriodoEnum.NOITE, periodoEnum0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PeriodoEnum[] periodoEnumArray0 = PeriodoEnum.values();
      assertEquals(2, periodoEnumArray0.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PeriodoEnum periodoEnum0 = PeriodoEnum.valueOf("MANHA");
      assertEquals("Manh\u00E3", periodoEnum0.getPeriodo());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PeriodoEnum periodoEnum0 = PeriodoEnum.NOITE;
      String string0 = periodoEnum0.getDescricao();
      assertEquals("noite", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      try { 
        PeriodoEnum.getPeriodoByDescricao("mani_");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Periodo: mani_, n\uFFFDo aplicavel
         //
         verifyException("br.com.teste.gft.enuns.PeriodoEnum", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PeriodoEnum periodoEnum0 = PeriodoEnum.getPeriodoByDescricao("manha");
      String string0 = periodoEnum0.getPeriodo();
      assertEquals("Manh\u00E3", string0);
  }
}
