/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 25 21:11:25 GMT 2020
 */

package br.com.teste.gft.enuns;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.teste.gft.enuns.TipoDePratoEnum;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TipoDePratoEnum_ESTest extends TipoDePratoEnum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TipoDePratoEnum[] tipoDePratoEnumArray0 = TipoDePratoEnum.values();
      assertEquals(4, tipoDePratoEnumArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TipoDePratoEnum tipoDePratoEnum0 = TipoDePratoEnum.valueOf("LADO");
      assertEquals(TipoDePratoEnum.LADO, tipoDePratoEnum0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TipoDePratoEnum tipoDePratoEnum0 = TipoDePratoEnum.BEBIDA;
      String string0 = tipoDePratoEnum0.getDescricao();
      assertEquals("Bebida", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TipoDePratoEnum tipoDePratoEnum0 = TipoDePratoEnum.LADO;
      Long long0 = tipoDePratoEnum0.getTipo();
      assertEquals(2L, (long)long0);
  }
}
