/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 25 21:09:44 GMT 2020
 */

package br.com.teste.gft.dialogo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.teste.gft.cardapio.ConstroiCardapio;
import br.com.teste.gft.dialogo.ConstroiDialogo;
import br.com.teste.gft.dialogo.Dialogo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Dialogo_ESTest extends Dialogo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Dialogo dialogo0 = new Dialogo();
      ConstroiCardapio constroiCardapio0 = new ConstroiCardapio();
      Injector.inject(dialogo0, (Class<?>) Dialogo.class, "constroiCardapio", (Object) constroiCardapio0);
      ConstroiDialogo constroiDialogo0 = new ConstroiDialogo();
      Injector.inject(dialogo0, (Class<?>) Dialogo.class, "constroiDialogo", (Object) constroiDialogo0);
      Injector.validateBean(dialogo0, (Class<?>) Dialogo.class);
      dialogo0.iniciaDialogo();
  }
}
