/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 25 21:07:27 GMT 2020
 */

package br.com.teste.gft.cardapio;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.teste.gft.cardapio.ConstroiCardapio;
import br.com.teste.gft.cardapio.OpcoaoCardapio;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ConstroiCardapio_ESTest extends ConstroiCardapio_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConstroiCardapio constroiCardapio0 = new ConstroiCardapio();
      List<OpcoaoCardapio> list0 = constroiCardapio0.constroiOpcoes();
      assertEquals(8, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ConstroiCardapio constroiCardapio0 = new ConstroiCardapio();
      String string0 = constroiCardapio0.constroiCardapio();
      assertEquals("Tipos de Prato | Manh\u00E3 | Noite |  \n 1 Entrada |Ovo |Bife |\n2 Lado |Torrada |Batata |\n3 Bebida |Caf\u00E9 |Vinho |\n4 Sobremesa |N\u00E3o Cont\u00E9m |Bolo |\n", string0);
  }
}
