/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 25 21:03:59 GMT 2020
 */

package br.com.teste.gft.cardapio;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.teste.gft.cardapio.OpcoaoCardapio;
import br.com.teste.gft.enuns.PeriodoEnum;
import br.com.teste.gft.enuns.TipoDePratoEnum;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OpcoaoCardapio_ESTest extends OpcoaoCardapio_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio();
      boolean boolean0 = opcoaoCardapio0.equals(opcoaoCardapio0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder0 = new OpcoaoCardapio.OpcoaoCardapioBuilder();
      OpcoaoCardapio opcoaoCardapio0 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      TipoDePratoEnum tipoDePratoEnum0 = TipoDePratoEnum.LADO;
      opcoaoCardapio0.setTipoDePrato(tipoDePratoEnum0);
      TipoDePratoEnum tipoDePratoEnum1 = opcoaoCardapio0.getTipoDePrato();
      assertEquals(TipoDePratoEnum.LADO, tipoDePratoEnum1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio();
      PeriodoEnum periodoEnum0 = PeriodoEnum.NOITE;
      opcoaoCardapio0.setPeriodo(periodoEnum0);
      PeriodoEnum periodoEnum1 = opcoaoCardapio0.getPeriodo();
      assertEquals(PeriodoEnum.NOITE, periodoEnum1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio();
      opcoaoCardapio0.setNome("OpcoaoCardapio(nome=null, tipoDePrato=null, periodo=null)");
      String string0 = opcoaoCardapio0.getNome();
      assertEquals("OpcoaoCardapio(nome=null, tipoDePrato=null, periodo=null)", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TipoDePratoEnum tipoDePratoEnum0 = TipoDePratoEnum.ENTRADA;
      PeriodoEnum periodoEnum0 = PeriodoEnum.NOITE;
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio("", tipoDePratoEnum0, periodoEnum0);
      String string0 = opcoaoCardapio0.getNome();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio();
      boolean boolean0 = opcoaoCardapio0.canEqual(opcoaoCardapio0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder0 = new OpcoaoCardapio.OpcoaoCardapioBuilder();
      OpcoaoCardapio opcoaoCardapio0 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      Object object0 = new Object();
      boolean boolean0 = opcoaoCardapio0.canEqual(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio();
      opcoaoCardapio0.getPeriodo();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio();
      String string0 = opcoaoCardapio0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio();
      opcoaoCardapio0.getTipoDePrato();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder0 = new OpcoaoCardapio.OpcoaoCardapioBuilder();
      PeriodoEnum periodoEnum0 = PeriodoEnum.MANHA;
      opcoaoCardapio_OpcoaoCardapioBuilder0.periodo(periodoEnum0);
      OpcoaoCardapio opcoaoCardapio0 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      OpcoaoCardapio opcoaoCardapio1 = new OpcoaoCardapio();
      boolean boolean0 = opcoaoCardapio0.equals(opcoaoCardapio1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio();
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder0 = OpcoaoCardapio.builder();
      PeriodoEnum periodoEnum0 = PeriodoEnum.NOITE;
      opcoaoCardapio_OpcoaoCardapioBuilder0.periodo(periodoEnum0);
      OpcoaoCardapio opcoaoCardapio1 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      boolean boolean0 = opcoaoCardapio0.equals(opcoaoCardapio1);
      assertFalse(opcoaoCardapio1.equals((Object)opcoaoCardapio0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder0 = OpcoaoCardapio.builder();
      PeriodoEnum periodoEnum0 = PeriodoEnum.MANHA;
      opcoaoCardapio_OpcoaoCardapioBuilder0.periodo(periodoEnum0);
      OpcoaoCardapio opcoaoCardapio0 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      OpcoaoCardapio opcoaoCardapio1 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      boolean boolean0 = opcoaoCardapio0.equals(opcoaoCardapio1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder0 = OpcoaoCardapio.builder();
      TipoDePratoEnum tipoDePratoEnum0 = TipoDePratoEnum.LADO;
      OpcoaoCardapio opcoaoCardapio0 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      opcoaoCardapio_OpcoaoCardapioBuilder0.tipoDePrato(tipoDePratoEnum0);
      OpcoaoCardapio opcoaoCardapio1 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      boolean boolean0 = opcoaoCardapio1.equals(opcoaoCardapio0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder0 = OpcoaoCardapio.builder();
      TipoDePratoEnum tipoDePratoEnum0 = TipoDePratoEnum.LADO;
      OpcoaoCardapio opcoaoCardapio0 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      opcoaoCardapio_OpcoaoCardapioBuilder0.tipoDePrato(tipoDePratoEnum0);
      OpcoaoCardapio opcoaoCardapio1 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      boolean boolean0 = opcoaoCardapio0.equals(opcoaoCardapio1);
      assertFalse(boolean0);
      assertFalse(opcoaoCardapio1.equals((Object)opcoaoCardapio0));
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TipoDePratoEnum tipoDePratoEnum0 = TipoDePratoEnum.SOBREMESA;
      PeriodoEnum periodoEnum0 = PeriodoEnum.NOITE;
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio("IO~dH/H", tipoDePratoEnum0, periodoEnum0);
      OpcoaoCardapio opcoaoCardapio1 = new OpcoaoCardapio();
      boolean boolean0 = opcoaoCardapio1.equals(opcoaoCardapio0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio();
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder0 = OpcoaoCardapio.builder();
      opcoaoCardapio_OpcoaoCardapioBuilder0.nome("OpcoaoCardapio(nome=null, tipoDePrato=null, periodo=null)");
      OpcoaoCardapio opcoaoCardapio1 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      boolean boolean0 = opcoaoCardapio1.equals(opcoaoCardapio0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio();
      boolean boolean0 = opcoaoCardapio0.equals("(9)S6IOV");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder0 = new OpcoaoCardapio.OpcoaoCardapioBuilder();
      PeriodoEnum periodoEnum0 = PeriodoEnum.MANHA;
      opcoaoCardapio_OpcoaoCardapioBuilder0.periodo(periodoEnum0);
      OpcoaoCardapio opcoaoCardapio0 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      opcoaoCardapio0.hashCode();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder0 = new OpcoaoCardapio.OpcoaoCardapioBuilder();
      TipoDePratoEnum tipoDePratoEnum0 = TipoDePratoEnum.ENTRADA;
      opcoaoCardapio_OpcoaoCardapioBuilder0.tipoDePrato(tipoDePratoEnum0);
      OpcoaoCardapio opcoaoCardapio0 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      opcoaoCardapio0.hashCode();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio();
      opcoaoCardapio0.setNome("(9)S6IOV");
      opcoaoCardapio0.hashCode();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio();
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder0 = OpcoaoCardapio.builder();
      OpcoaoCardapio opcoaoCardapio1 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      boolean boolean0 = opcoaoCardapio1.equals(opcoaoCardapio0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      OpcoaoCardapio opcoaoCardapio0 = new OpcoaoCardapio();
      String string0 = opcoaoCardapio0.toString();
      assertEquals("OpcoaoCardapio(nome=null, tipoDePrato=null, periodo=null)", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder0 = OpcoaoCardapio.builder();
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder1 = opcoaoCardapio_OpcoaoCardapioBuilder0.nome("OpcoaoCardapio(nome=null, tipoDePrato=null, periodo=null)");
      OpcoaoCardapio opcoaoCardapio0 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      OpcoaoCardapio opcoaoCardapio1 = opcoaoCardapio_OpcoaoCardapioBuilder1.build();
      boolean boolean0 = opcoaoCardapio0.equals(opcoaoCardapio1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder0 = OpcoaoCardapio.builder();
      String string0 = opcoaoCardapio_OpcoaoCardapioBuilder0.toString();
      assertEquals("OpcoaoCardapio.OpcoaoCardapioBuilder(nome=null, tipoDePrato=null, periodo=null)", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      OpcoaoCardapio.OpcoaoCardapioBuilder opcoaoCardapio_OpcoaoCardapioBuilder0 = OpcoaoCardapio.builder();
      TipoDePratoEnum tipoDePratoEnum0 = TipoDePratoEnum.LADO;
      opcoaoCardapio_OpcoaoCardapioBuilder0.tipoDePrato(tipoDePratoEnum0);
      OpcoaoCardapio opcoaoCardapio0 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      OpcoaoCardapio opcoaoCardapio1 = opcoaoCardapio_OpcoaoCardapioBuilder0.build();
      boolean boolean0 = opcoaoCardapio0.equals(opcoaoCardapio1);
      assertTrue(boolean0);
  }
}
